project_name: Alto — Eleventy Documentation theme
default_og_image: /assets/images/uploads/alto.png
favicon:
  small_icon: /assets/images/meta/favicon-16x16.png
  large_icon: /assets/images/meta/favicon-32x32.png
  apple_touch_icon: /assets/images/meta/apple-touch-icon.png
  shortcut_icon: /assets/images/meta/favicon.ico